#!/bin/sh

set -e
set -x

usage()
{
	cat <<'EOUSAGE'
Usage:	build-cloudstack -c commit-id -d srcdir -f forked-dir -r username@hostname -s username@hostname -t username@hostname -a username@hostname
...and stuff.
EOUSAGE
}

unset srcdir commit_id forked remote1 remote2 remote3 remote4 remote5 remote6
while getopts 'c:d:f:1:2:3:4:5:6:' o; do
	case "$o" in
		c)
			if [ "${OPTARG#-}" != "$OPTARG" ]; then
				echo "The commit ID cannot start with a dash" 1>&2
				usage 1>&2
				exit 1
			fi
			commit_id="$OPTARG"
			;;

		d)
			srcdir="$OPTARG"
			;;

		f)
			forked="$OPTARG"
			;;

		1)
			remote1="$OPTARG"
			;;
		2)
			remote2="$OPTARG"
			;;
		3)
			remote3="$OPTARG"
			;;
		4)
			remote4="$OPTARG"
			;;
		5)
			remote5="$OPTARG"
			;;
		6)
			remote6="$OPTARG"
			;;
		*)
			usage 1>&2
			exit 1
			;;
	esac
done

if [ -z "$commit_id" ] || [ -z "$srcdir" ] || [ -z "$forked" ] || [ -z "$remote1" ] || [ -z "$remote2" ]; then
	usage 1>&2
	exit 1
fi

cd -- "$srcdir"
git checkout "$commit_id"
mvn clean install

cp -- target/cloud-plugin-storage-volume-storpool-*.0.jar "$forked/plugins/storage/volume/"
scp -- target/cloud-plugin-storage-volume-storpool-*.jar "$remote1:/usr/share/cloudstack-agent/lib/"
ssh -- "$remote1" systemctl restart cloudstack-agent
scp -- target/cloud-plugin-storage-volume-storpool-*.jar "$remote2:/usr/share/cloudstack-agent/lib/"
ssh -- "$remote2" systemctl restart cloudstack-agent

if [ -n "$remote3" ]; then
	scp -- target/cloud-plugin-storage-volume-storpool-*.jar "$remote3:/usr/share/cloudstack-agent/lib/"
	ssh -- "$remote3" systemctl restart cloudstack-agent
fi

if [ -n "$remote4" ]; then
	scp -- target/cloud-plugin-storage-volume-storpool-*.jar "$remote4:/usr/share/cloudstack-agent/lib/"
	ssh -- "$remote4" systemctl restart cloudstack-agent
fi

if [ -n "$remote5" ]; then
	scp -- target/cloud-plugin-storage-volume-storpool-*.jar "$remote5:/usr/share/cloudstack-agent/lib/"
	ssh -- "$remote5" systemctl restart cloudstack-agent
fi

if [ -n "$remote6" ]; then
	scp -- target/cloud-plugin-storage-volume-storpool-*.jar "$remote6:/usr/share/cloudstack-agent/lib/"
	ssh -- "$remote6" systemctl restart cloudstack-agent
fi